TITLE: Recruitment Calc
NOTIFICATION_DESCRIPTION: Press to quit.
NOT_FOUND_TAGS: >
    There are no recognized tags. Please call me when\n
    "Recruit Now" is in progress at Arknights.
CHECK_NOTIICATION: You can send me away in the push notification.
